name: npm-test

on:
  push:
    branches:
    - main
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USER_ID: ${{ secrets.USER_ID }}